# Generated by Django 4.1 on 2022-08-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrawingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, unique=True, verbose_name="Title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="images/Error404.jpg", upload_to="images"
                    ),
                ),
                ("video", models.FileField(blank=True, upload_to="videos")),
                (
                    "url_1_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Url 1 name"
                    ),
                ),
                (
                    "url_1",
                    models.CharField(blank=True, max_length=200, verbose_name="Url 1"),
                ),
            ],
        ),
    ]
