# Generated by Django 4.1 on 2023-03-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingitem',
            name='type',
            field=models.CharField(default='Acuarela', max_length=200, verbose_name='Type'),
        ),
    ]
