# Generated by Django 4.1 on 2023-03-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0003_alter_drawingitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingcategory',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Description'),
        ),
    ]
