# Generated by Django 4.1 on 2023-03-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0004_drawingcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingcategory',
            name='priority',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
