# Generated by Django 4.1 on 2023-03-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0005_drawingcategory_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawingcategory',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
