# Generated by Django 3.2.18 on 2023-04-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0006_alter_drawingcategory_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingcategory',
            name='short_title',
            field=models.CharField(default='tinta', max_length=200, verbose_name='Short title'),
            preserve_default=False,
        ),
    ]
