# Generated by Django 3.2.18 on 2023-04-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0007_drawingcategory_short_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawingitem',
            name='url_1',
        ),
        migrations.RemoveField(
            model_name='drawingitem',
            name='url_1_name',
        ),
        migrations.AddField(
            model_name='drawingcategory',
            name='image',
            field=models.ImageField(default='images/Error404.jpg', upload_to='images'),
        ),
    ]
