# Generated by Django 3.2.18 on 2023-04-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0008_auto_20230406_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingitem',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
