# Generated by Django 3.2.18 on 2023-08-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0009_drawingitem_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingcategory',
            name='background',
            field=models.ImageField(default='media/images/Error404', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='drawingcategory',
            name='image',
            field=models.ImageField(default='media/images/Error404', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='drawingitem',
            name='image',
            field=models.ImageField(default='media/images/Error404', upload_to='images'),
        ),
    ]
